# Generated by Django 3.1 on 2020-08-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0002_auto_20200820_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order_journal',
            name='next_user',
        ),
        migrations.RemoveField(
            model_name='work_order_journal',
            name='prev_user',
        ),
    ]
