# Generated by Django 3.1 on 2020-08-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_auto_20200820_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order_journal',
            name='next_user',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='work_order_journal',
            name='prev_user',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
