# Generated by Django 3.1 on 2020-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0004_auto_20200820_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='action',
            field=models.CharField(blank=True, choices=[('f', 'Forward'), ('r', 'Return'), ('o', 'Other')], default='f', help_text='Select action', max_length=1),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='status',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='wo_number',
            field=models.CharField(help_text='Enter WO number(Prodxxxx)', max_length=20, null=True),
        ),
    ]
