# Generated by Django 3.1 on 2020-08-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0005_auto_20200822_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='action',
            field=models.CharField(blank=True, choices=[('f', 'Forward'), ('r', 'Return'), ('o', 'Other')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='dest_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.section'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='priority',
            field=models.CharField(blank=True, choices=[('n', 'Normal'), ('e', 'Emergency'), ('s', 'Shutdown'), ('o', 'Other')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='problem',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='wo_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
