# Generated by Django 3.1 on 2020-08-23 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workOrder', '0006_auto_20200823_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order_journal',
            name='next_user',
        ),
        migrations.RemoveField(
            model_name='work_order_journal',
            name='prev_user',
        ),
        migrations.AddField(
            model_name='work_order_completion',
            name='wO_completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.work_order'),
        ),
        migrations.AddField(
            model_name='work_order_journal',
            name='concern_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work_order_journal',
            name='wO_on_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.work_order'),
        ),
    ]
