# Generated by Django 3.1 on 2020-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0008_work_order_completion_acted_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order',
            name='action',
        ),
        migrations.AddField(
            model_name='work_order_journal',
            name='action',
            field=models.CharField(blank=True, choices=[('f', 'Forward'), ('r', 'Return'), ('o', 'Other')], default='f', max_length=1),
        ),
    ]
