# Generated by Django 3.1 on 2020-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0009_auto_20200824_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_journal',
            name='comment',
            field=models.TextField(help_text='Enter comment', max_length=200, null=True),
        ),
    ]
