# Generated by Django 3.1 on 2020-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0010_auto_20200824_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='current_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
