# Generated by Django 3.1 on 2020-08-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0011_work_order_current_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='approver',
            new_name='forward_path',
        ),
    ]
