# Generated by Django 3.1 on 2020-08-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0015_auto_20200828_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_completion',
            name='manPower',
            field=models.TextField(help_text='Man power name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='work_order_completion',
            name='material',
            field=models.TextField(help_text='Enter material', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work_order_completion',
            name='tool',
            field=models.TextField(help_text='Enter action', max_length=500, null=True),
        ),
    ]
