# Generated by Django 3.1 on 2020-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0016_auto_20200831_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='date_close',
            field=models.DateField(null=True),
        ),
    ]
