# Generated by Django 3.1 on 2020-08-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0017_work_order_date_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='finish_user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='work_order_completion',
            name='manPower',
            field=models.TextField(help_text='Man power name', max_length=100, null=True),
        ),
    ]
