# Generated by Django 3.1 on 2020-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0018_auto_20200901_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order_completion',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In progress'), ('f', 'Finish')], default='f', max_length=1),
        ),
    ]
