# Generated by Django 3.1 on 2020-08-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0019_work_order_completion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='finish_user_id',
            new_name='executor_user_id',
        ),
    ]
