# Generated by Django 3.1 on 2020-09-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0021_auto_20200901_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order_completion',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In progress'), ('h', 'Finish')], default='h', max_length=1),
        ),
    ]
