# Generated by Django 3.1 on 2020-09-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0022_auto_20200901_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='date_close',
            new_name='date_finish',
        ),
    ]
