# Generated by Django 3.1 on 2020-09-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0024_auto_20200912_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
