# Generated by Django 3.1 on 2020-09-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_auto_20200919_1926'),
        ('workOrder', '0026_auto_20200919_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='status_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.action'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
