# Generated by Django 3.1 on 2020-09-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_department_initial'),
        ('workOrder', '0028_auto_20200920_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='status_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.action'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='status',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
