# Generated by Django 3.1 on 2020-09-20 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0011_auto_20200920_1616'),
        ('workOrder', '0031_auto_20200920_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_order_completion',
            new_name='Wo_completion',
        ),
        migrations.RenameModel(
            old_name='Work_order_journal',
            new_name='Wo_journal',
        ),
    ]
