# Generated by Django 3.1 on 2020-09-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workOrder', '0032_auto_20200920_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wo_instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Enter action', max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.work_order')),
            ],
        ),
    ]
