# Generated by Django 3.1 on 2020-09-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_auto_20200920_1616'),
        ('workOrder', '0033_wo_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wo_completion',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.action'),
        ),
    ]
