# Generated by Django 3.1 on 2020-09-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_wo_priority'),
        ('workOrder', '0034_auto_20200921_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.wo_priority'),
        ),
    ]
