# Generated by Django 3.1 on 2020-09-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0036_auto_20200921_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wo_completion',
            name='action',
        ),
        migrations.AddField(
            model_name='wo_completion',
            name='activity',
            field=models.TextField(help_text='Enter activity', max_length=1000, null=True),
        ),
    ]
