# Generated by Django 3.1 on 2020-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0037_auto_20200922_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wo_completion',
            old_name='wO_completed',
            new_name='work_order',
        ),
        migrations.RenameField(
            model_name='wo_journal',
            old_name='wO_on_process',
            new_name='work_order',
        ),
        migrations.AlterField(
            model_name='wo_instruction',
            name='instruction',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
