# Generated by Django 3.1 on 2020-09-11 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of section(eg. Maintenance)', max_length=50, null=True)),
                ('initial', models.CharField(help_text='Enter initial of section(eg. Mntc)', max_length=5, null=True)),
                ('description', models.CharField(help_text='Enter description of department', max_length=200, null=True)),
                ('role', models.CharField(blank=True, choices=[('e', 'Executor'), ('o', 'Originator'), ('a', 'Any')], default='o', help_text='Select role', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of section(eg. Electrical & Instrumentation)', max_length=50, null=True)),
                ('initial', models.CharField(help_text='Enter initial of section(eg. Elins)', max_length=5, null=True)),
                ('description', models.CharField(help_text='Enter description of section', max_length=200, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.department')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField(null=True)),
                ('initial', models.CharField(max_length=3, null=True)),
                ('forward_path', models.CharField(max_length=3, null=True)),
                ('reverse_path', models.CharField(max_length=3, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
