# Generated by Django 3.1 on 2020-09-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0024_auto_20200912_1501'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileutility',
            name='action',
            field=models.ManyToManyField(help_text='Select actions', to='workOrder.Status'),
        ),
    ]
