# Generated by Django 3.1 on 2020-09-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_profileutility_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileutility',
            name='forward_path',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profileutility',
            name='reverse_path',
            field=models.IntegerField(null=True),
        ),
    ]
