# Generated by Django 3.1 on 2020-09-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20200912_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='profileutility',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='profileutility',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='section',
            name='initial',
        ),
    ]
