# Generated by Django 3.1 on 2020-09-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20200917_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='role',
        ),
    ]
