# Generated by Django 3.1 on 2020-09-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_remove_department_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileutility',
            old_name='action',
            new_name='actions',
        ),
    ]
