# Generated by Django 3.1 on 2020-09-19 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0025_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0006_auto_20200919_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUtility',
            new_name='Profile',
        ),
    ]
