# Generated by Django 3.1 on 2020-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_auto_20200919_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Action(eg. Open, Close, Reject...)', max_length=20, null=True)),
                ('description', models.CharField(help_text='Enter description of Action', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
