# Generated by Django 3.1 on 2020-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actions',
            field=models.ManyToManyField(help_text='Select actions', to='utility.Action'),
        ),
    ]
