# Generated by Django 3.1 on 2020-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_auto_20200920_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wo_priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of section(eg. Normal, Emergency)', max_length=20, null=True)),
                ('description', models.CharField(help_text='Enter description of priority', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
